spring.application.name=store
server.port=${PORT:8081}
# Vô hiệu hóa hoàn toàn việc tìm kiếm Database khi khởi động
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Nếu anh vẫn dùng Thymeleaf để hiện giao diện cho "đong đưa"
spring.thymeleaf.cache=false